apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-pod
spec:
  podSelector:
      matchlables: 
         app: nginx
  Ingress: 
  - from: 
       - podSelector:
            matchLabels: 
               app: backed
    ports:
       - port: 8080
         protocol: TCP 
  policyTypes:
  - Ingress
     
